### ISSUE TITLE
Wrong ports restriction?

### ISSUE THREAD

**Issue by kurnevsky** [zugz/tox-DHTAnnouncements#1]
> On receiving a Route Request packet, we check that the addressee port is in the range 33445-33454, and if we send a Route Deliver packet to the addressee IP/Port with sendback set to a random 24-byte nonce followed by the addressee IP/Port, authenticated and encrypted using the nonce and the same symmetric key used to generate Ping IDs above.

> The restriction on ports is to prevent any abuse which could be enabled by having attackers able to cause DHT nodes to send largely attacker-determined packets to arbitrary ports where they might be interpreted under other protocols.

It seems it's wrong to allow relaying only to this port range. The protocol doesn't oblige to use this range and it can be changed via `tox_options_set_start_port` and `tox_options_set_end_port` functions or via `tox-bootstrapd.conf`. Also with cone NAT this port is likely to be different, but it allows incoming connections.

As a possible alternative - can we allow relaying only to those nodes that we have in our kbuckets, the same way we relay `DHT Request` packets? In this case we won't be able to relay all announcement-related requests via random nodes. The `Relaying` section says only that it helps to reach nodes that can't be reached directly. Is there a security reason why we can't announce using direct connection and relays only for unreachable nodes?

**Comment by zugz** [comment]
* Monday, 2018-11-05 at 01:11 -0800 - Evgeny Kurnevsky <notifications@github.com>:

>It seems it's wrong to allow relaying only to this port range. The 
>protocol doesn't oblige to use this range and it can be changed via 
>`tox_options_set_start_port` and `tox_options_get_end_port` functions 
>or via `tox-bootstrapd.conf`.

True, it isn't currently part of the spec. But we could add to the spec 
that this port range is to be preferred. It doesn't really matter if 
some nodes use other ports - it just means they won't be used for 
storing announcements.

>As a possible alternative - can we allow relaying only to those nodes 
>that we have in our kbuckets, the same way we relay `DHT Request` 
>packets?

Consider the case of TCP clients who can't use UDP at all. They have to 
relay their announcements via TCP servers. They can't expect the nodes 
they want to announce at to be in the close lists of the TCP servers.

Note that the onion currently allows arbitrary relaying - TCP servers 
and DHT nodes will accept requests (in the form of onion packets) to 
relay to arbitrary hosts on arbitrary ports. But this seems like 
a really bad idea, so I didn't want to replicate it... we already saw 
one bad consequence for the tox protocol with the bug you found and 
fixed, and there might well be unpleasant consequences for other 
protocols. I don't like the port restriction solution either, but 
I don't see a better one. We could demand more restrictions on the 
relayed packet, like starting with "TOXTOXTOXTOX", but can we really be 
sure that no protocol won't ignore the part we specify and do something 
bad with the part the relay requester gets to specify?

>In this case we won't be able to relay all announcement-related 
>requests via random nodes. The `Relaying` section says only that it 
>helps to reach nodes that can't be reached directly. Is there 
>a security reason why we can't announce using direct connection and 
>relays only for unreachable nodes?

Not a security reason, but there is a problem with that: there may be 
nodes which we can talk to directly even though most peers can't. In 
particular, this happens if we're announcing to an announcement public 
key which happens to be close to our DHT key - many of the nodes in our 
close list will be there as a result of incoming connections, and so our 
packets may make it through their firewall even though others' won't. 
There may be other ways to solve this problem (e.g. the DHT hardening 
technique), but relaying everything seems cleanest and most reliable.

Note that relaying also has the bonus effect of hiding the IP address 
(though not the DHT key) of an announcer/searcher from the announce 
nodes, which makes it a bit more complicated and expensive to find out 
the IP addresses of the friends of your friends (but by no means 
prevents this entirely!).

**Comment by kurnevsky** [comment]
> It doesn't really matter if some nodes use other ports - it just means they won't be used for storing announcements.

Here are some stats from the current tox network (from my laptop):
```
Total nodes: 2479 (unique keys)
Reachable nodes: 379 (unique keys)
Total nodes with port 33445-33454: 1541 (unique addresses)
Total nodes with other port: 1380 (unique addresses)
Reachable nodes with port 33445-33454: 265 (unique addresses)
Reachable nodes with other port: 117 (unique addresses)
```
So at best we will lose 1/3 of total tox nodes. Do you think it's affordable?

> Consider the case of TCP clients who can't use UDP at all. They have to relay their announcements via TCP servers. They can't expect the nodes they want to announce at to be in the close lists of the TCP servers.

But it seems TCP is not very useful for amplification attacks, is it? I suppose overhead for TCP connection will be bigger then amplification coefficient (or at least comparable). So we can allow to send to any node from TCP relay.

**Comment by zugz** [comment]
* Monday, 2018-11-05 at 11:27 -0800 - Evgeny Kurnevsky <notifications@github.com>:

>Reachable nodes with port 33445-33454: 265 (unique addresses)
>Reachable nodes with other port: 117 (unique addresses)

Hmm, that is worse than I expected. What other ports are in use? We 
could possibly make exceptions for a few ports like 80 and 443...

>> Consider the case of TCP clients who can't use UDP at all. They have 
>> to relay their announcements via TCP servers. They can't expect the 
>> nodes they want to announce at to be in the close lists of the TCP 
>> servers.
>
>But it seems TCP is not very useful for amplification attacks, is it? 
>I suppose overhead for TCP connection will be bigger then amplification 
>coefficient (or at least comparable).

I'm not worried about amplification attacks here - the amplification 
coefficient of the relay packet is about than 1. I'm worried about 
tickling other protocols. Don't you think that's a reasonable worry?

**Comment by kurnevsky** [comment]
> Hmm, that is worse than I expected. What other ports are in use? We could possibly make exceptions for a few ports like 80 and 443...

They are very different. From reachable nodes:
```
1025 1048 1080 1092 1186 2257 2306 2307 2413 2527 3146 3331 3481 3851 4124 4883 5655 6781 6877 7225 7627 7978 9235 9248 10001 10073 10645 11500 11742 13185 13283 13315 13681 13742 14811 14996 15781 17143 17409 17687 17807 18259 18278 18610 18805 21167 21353 21922 22648 23185 23609 24287 25445 25643 25665 25833 26361 28873 29409 29702 30029 30271 31841 33556 34249 34254 36332 36587 36895 38873 39791 40051 40441 43268 43562 43593 44071 45589 48683 48762 49152 51593 52624 52697 52930 53222 53509 54249 54474 54492 56399 57469 57934 59188 59441 59495 60851 61424 62535 63073 65163
```

> I'm not worried about amplification attacks here - the amplification coefficient of the relay packet is about than 1. I'm worried about tickling other protocols. Don't you think that's a reasonable worry?

It seems we can workaround it. Let's say node A wants to send packet to node C via node B. Then A can provide public key of C to B. Then B can encrypt data with this public key and random secret key before sending. This makes it almost impossible to make B to send packet that will be valid for some other protocol.

**Comment by kurnevsky** [comment]
> Then B can encrypt data with this public key and random secret key before sending.

Or B can even use it's own DHT key, the packet will be random-looking due to random nonce.

**Comment by zugz** [comment]
* Monday, 2018-11-05 at 12:08 -0800 - Evgeny Kurnevsky <notifications@github.com>:

>> What other ports are in use?
>
>They are very different. From reachable nodes:

Yes of course, many nodes accepting incoming connections will be behind 
full cone NATs. So the ports will be random.

>> I'm worried about tickling other protocols.
>
>It seems we can workaround it. Let's say node A wants to send packet to 
>node C via node B. Then A can provide public key of C to B. Then B can 
>encrypt data with this public key and random secret key before sending. 
>This makes it almost impossible to make B to send packet that will be 
>valid for some other protocol.

Right! Makes the packet a bit heavier, but yes, I think this must be the 
correct solution. So we can just wrap these packets in DHT packets. 
Probably we can then simplify this bit of the protocol considerably... 
let me think it through again.

**Comment by zugz** [comment]
* Monday, 2018-11-05 at 12:49 -0800 - zugz <notifications@github.com>:

>So we can just wrap these packets in DHT packets.

Although - then the packet starts with the relayer's DHT key, which an 
attacker can choose to some extent by picking an appropriate DHT node. 
So maybe we should use a random key. It can actually just be a symmetric 
encryption key.

So I'm thinking: drop the sendback system, and just have two packets; 
"route request" as currently, and a new "delivery" packet which starts 
with a random symmetric encryption key followed by a payload encrypted 
with that key and the zero nonce (it's ok to use a fixed nonce since we 
only use this key once). The payload contains the IP/Port of the 
original sender of the route request, followed by the data from that 
request. A reply can be made by a route request to the source of the 
delivery packet, asking to route to the sender IP/Port given in that 
packet.

See any problems with this?

Alternatively we could keep the sendbacks, and just encrypt the Delivery 
and Route Response packets. Having sendbacks complicates the system and 
makes it a little heavier, in return for the illusion of security... 
I don't think it's worth it.

**Comment by kurnevsky** [comment]
> See any problems with this?

I think in the future we will want to unify UDP packets format to (PublicKey in Elligator representation, Nonce, Payload encrypted with addressee SecretKey), without any additional info. This will make packets indistinguishable from random which should help with protection against Deep Packets Inspection. So perhaps we shouldn't go far from PublicKey encryption? Or even better if we make breaking changes then we can switch to this format.

I'm not sure though should it be just an additional layer of encryption with temporary key or we can use self DHT PublicKey to encrypt such packets. But anyway we will have to know node's PublicKey to send a packet.

**Comment by zugz** [comment]
* Tuesday, 2018-11-06 at 00:31 -0800 - Evgeny Kurnevsky <notifications@github.com>:

>I think in the future we will want to unify UDP packets format to 
>(PublicKey in Elligator representation

Nice idea. Though there are also other parts of the protocol which would 
need adapting to handle deep packet inspection, e.g. the steadily 
increasing nonces in net crypto encrypted packets.

> So perhaps we shouldn't go far from PublicKey encryption? 

We'd still want to use a fresh random key, so if we used public key 
encryption we'd have to calculate the combined key each time we receive 
one of the packets, which is moderately computationally expensive. With 
the symmetric approach we get uniform randomness for free, and no 
computational costs. I don't really see a downside.

**Comment by kurnevsky** [comment]
> e.g. the steadily increasing nonces in net crypto encrypted packets.

We can use random nonces there as well.

> With the symmetric approach we get uniform randomness for free, and no computational costs. I don't really see a downside.

That means that the intermediate node won't know addressee PublicKey. But ok, later if we unify UDP packets we can change route packet to contain this PublicKey. The other things that came to my mind are that anyone can send an announce packet to a node without knowing it's PublicKey and that a passive observer (e.g. internet provider) will be able to decrypt these packets. Though right now I can't see a particular case when it might be bad.

By the way, is it really expensive to calculate combined key? If we want to protect against DPI probably we will have to generate a new key for each packet. Also as far as I understand the noise protocol should generate a new key for each message.
